local_data_path:
  cifar_10_path: /home/ruiliu/Development/mtml-tf/dataset/cifar-10
  imagenet_t10k_img_path: /home/ruiliu/Development/mtml-tf/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /home/ruiliu/Development/mtml-tf/dataset/imagenet10k
  imagenet_t10k_label_path: /home/ruiliu/Development/mtml-tf/dataset/imagenet10k-label.txt
  imagenet_t1k_img_path: /home/ruiliu/Development/mtml-tf/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /home/ruiliu/Development/mtml-tf/dataset/imagenet1k
  imagenet_t1k_label_path: /home/ruiliu/Development/mtml-tf/dataset/imagenet1k-label.txt
  mnist_train_img_path: /home/ruiliu/Development/mtml-tf/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /home/ruiliu/Development/mtml-tf/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /home/ruiliu/Development/mtml-tf/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /home/ruiliu/Development/mtml-tf/dataset/mnist-t10k-labels.idx1-ubyte

remote_data_path:
  cifar_10_path: /tank/local/ruiliu/dataset/cifar-10
  imagenet_t10k_bin_path: /tank/local/ruiliu/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /tank/local/ruiliu/dataset/imagenet10k
  imagenet_t10k_label_path: /tank/local/ruiliu/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /tank/local/ruiliu/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /tank/local/ruiliu/dataset/imagenet1k
  imagenet_t1k_label_path: /tank/local/ruiliu/dataset/imagenet1k-label.txt
  mnist_train_img_path: /tank/local/ruiliu/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /tank/local/ruiliu/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /tank/local/ruiliu/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /tank/local/ruiliu/dataset/mnist-t10k-labels.idx1-ubyte

hyperband:
  resource_conf: 81
  down_rate: 3
  pack_rate: 9
  # policy: none, random, bs, knn
  schedule_policy: bs

hypermeter:
  #img_width and img_height differs for dataset
  img_width: 32
  img_height: 32
  num_channel: 3
  #num_class differs for dataset
  num_class: 10
  random_seed: 10000
  model_type:
    - mlp
  activation:
    - sigmoid
    - leaky_relu
    - tanh
    - relu
  optimizer:
    - Adam
    - SGD
    - Adagrad
    - Momentum
  num_model_layer:
    - 1
  batch_size:
    - 20
    - 25
    - 30
    - 35
    - 40
    - 45
    - 50
    - 55
    - 60
    - 65
    - 70
  learning_rate:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
    - 0.01
    - 0.1
